LABEL_UNREAD = 'UNREAD'
LABEL_INBOX = 'INBOX'
LABEL_TRASH = 'TRASH'

# Actions
ACTION_TRASH = 'TRASH'
ACTION_ARCHIVE = 'ARCHIVE'
ACTION_READ = 'READ'
ACTION_UNREAD_TRASHED = 'U_TRASHED'
ACTION_UNREAD_READ = 'U_READ'
ACTION_UNREAD_ARCHIVED = 'U_ARCHIVED'

MODIFY_EMAIL_ACTIONS = [
    (ACTION_ARCHIVE, 'Archive'),
    (ACTION_READ, 'Read'),
    (ACTION_TRASH, 'Trash')
]
