# Generated by Django 2.1.7 on 2019-04-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_email_list_unsubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='background_color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='label',
            name='text_color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='label',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User')], default='system', max_length=6),
        ),
    ]
