# Generated by Django 2.1.7 on 2019-04-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_auto_20190406_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='google_id',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='email',
            name='thread_id',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('google_id', 'thread_id')},
        ),
    ]
