# Generated by Django 2.1.7 on 2019-05-07 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0006_auto_20190407_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=16)),
                ('thread_id', models.CharField(max_length=16)),
                ('locked', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
