# Generated by Django 2.1.7 on 2019-05-26 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0008_auto_20190507_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifiedEmailBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_of_emails', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('ARCHIVE', 'Archive'), ('READ', 'Read'), ('SPAM', 'Spam'), ('TRASH', 'Trash')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
